on: [ push, pull_request ]

jobs:
  build:
    runs-on: windows-2025
    steps:      
      - uses: actions/checkout@v6
      
      - uses: microsoft/setup-msbuild@v3
        with:
          vs-version: # optional
          msbuild-architecture: # optional, default is x86
      
      - uses: NuGet/setup-nuget@v4.0
      
      - name: debug step
        working-directory: src
        run: dir

      - name: Restore Packages
        working-directory: src
        run: nuget restore ShutdownTimerClassic.sln

      - name: Build Solution
        working-directory: src
        run: |
          msbuild.exe ShutdownTimerClassic.sln /p:platform="Any CPU" /p:configuration="Debug"

      - uses: actions/upload-artifact@v7
        with:
          path: src
          compression-level: 9
          include-hidden-files: true
