on: [ push, pull_request ]

jobs:
  build:
    runs-on: windows-2025-vs2026
    steps:      
      - name: Setup project
        uses: actions/checkout@v6
      
      - name: Setup MSBuild
        uses: microsoft/setup-msbuild@v3
        with:
          vs-version: # optional
          msbuild-architecture: # optional, default is x86
      
      - name: Setup NuGet
        uses: NuGet/setup-nuget@v4.0

      - name: Restore Packages
        working-directory: src
        run: nuget restore ShutdownTimerClassic.sln

      - name: Build Solution
        working-directory: src
        run: |
          msbuild.exe ShutdownTimerClassic.sln /p:platform="Any CPU" /p:configuration="Debug"

      - name: Upload build artifacts
        uses: actions/upload-artifact@v7
        with:
          path: src/bin/Debug
          compression-level: 9
          include-hidden-files: true
